version: "3.3"
services:

  # Redis
  awes-demo-redis:
    restart: always
    hostname: awes-demo-redis
    container_name: awes-demo-redis
    image: redis:4.0-alpine
    expose:
      - "6379"
    volumes:
      - ./docker/redis:/data
    networks:
      awes_demo:
        ipv4_address: 172.29.1.2

  # MYSQL
  awes-demo-mysql:
    restart: always
    hostname: awes-demo-mysql
    container_name: awes-demo-mysql
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "5307:3306"
      - "53060:33060"
    command: "--innodb_use_native_aio=0"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: awes
      MYSQL_DATABASE: awes
      MYSQL_USER: awes
      MYSQL_PASSWORD: awes
    networks:
      awes_demo:
        ipv4_address: 172.29.1.3

  # PhpMyAdmin
  awes-demo-pma:
    restart: always
    hostname: awes-demo-pma
    container_name: awes-demo-pma
    image: phpmyadmin/phpmyadmin:4.6
    links:
      - awes-demo-mysql:db
    ports:
      - "5081:80"
    networks:
      awes_demo:
        ipv4_address: 172.29.1.4

  # PHP
  awes-demo-php:
    restart: always
    hostname: awes-demo-php
    container_name: awes-demo-php
    image: awescodehub/php-7.2-fpm
    expose:
      - "9000"
    volumes:
      - ./:/app
    links:
      - awes-demo-redis
      - awes-demo-mysql
    networks:
      awes_demo:
        ipv4_address: 172.29.1.5

  # supervisor
#  awes-demo-supervisor:
#    restart: always
#    hostname: awes-demo-supervisor
#    container_name: awes-demo-supervisor
#    build: ./docker/supervisor
#    image: awescrm:supervisor
#    expose:
#      - "9001"
#    volumes:
#      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
#      - ./:/app
#    networks:
#      awes_demo:
#        ipv4_address: 172.29.1.6

  # NGINX
  awes-demo-nginx:
    restart: always
    hostname: awes-demo-nginx
    container_name: awes-demo-nginx
    image: nginx:1.13
    ports:
      - "5080:5080"
      - "5443:5443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./:/app
    links:
      - awes-demo-pma
      - awes-demo-php
    networks:
      awes_demo:
        ipv4_address: 172.29.1.7

networks:
  awes_demo:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/24
